services:
  db:
    image: postgres:15
    container_name: rakoo-db
    restart: always
    environment:
      POSTGRES_USER: rakoo_user
      POSTGRES_PASSWORD: rakoo_password
      POSTGRES_DB: rakoo_db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: rakoo-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: rakoo-frontend
    ports:
      - "3001:3000"
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: