services:
  db:
    image: postgres:15
    container_name: rakoo-db
    environment:
      POSTGRES_USER: rakoo_user
      POSTGRES_PASSWORD: rakoo_password
      POSTGRES_DB: rakoo_db
    ports:
      - "5430:5432"
    networks:
      - rakoo-net
    volumes:
      - ./backend/db.sql:/docker-entrypoint-initdb.d/init.sql

  ai_model:
    build: ./ai
    container_name: rakoo-ai
    ports:
      - "8000:8000"
    networks:
      - rakoo-net

  backend:
    build: ./backend
    container_name: rakoo-backend
    environment:
      - AI_MODEL_URL=http://rakoo-ai:8000/predict
      - DATABASE_URL=postgresql://rakoo_user:rakoo_password@rakoo-db:5432/rakoo_db
    ports:
      - "5000:5000"
    depends_on:
      - db
      - ai_model
    networks:
      - rakoo-net

  frontend:
    build: ./frontend
    container_name: rakoo-frontend
    ports:
      - "3001:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - rakoo-net

networks:
  rakoo-net:
    driver: bridge